export const SET_SHUFFLED_CARDS = 'SET_SHUFFLED_CARDS';
export const SET_CARDS_ON_TABLE = 'SET_CARDS_ON_TABLE';
export const SET_SELECTED_CARD = 'SET_SELECTED_CARD';
export const SET_BETTING_COINS = 'SET_BETTING_COINS';
export const SET_CURRENT_COINS = 'SET_CURRENT_COINS';
export const SET_BET_COINS = 'SET_BET_COINS';
export const SET_GUESS = 'SET_GUESS';