const Config = {
 cards: [
     // HEARTS
    {number: 1, symbol: 'hearts'},
    {number: 2, symbol: 'hearts'},
    {number: 3, symbol: 'hearts'},
    {number: 4, symbol: 'hearts'},
    {number: 5, symbol: 'hearts'},
    {number: 6, symbol: 'hearts'},
    {number: 7, symbol: 'hearts'},
    {number: 8, symbol: 'hearts'},
    {number: 9, symbol: 'hearts'},
    {number: 10, symbol: 'hearts'},
    {number: 12, symbol: 'hearts'},
    {number: 13, symbol: 'hearts'},
    {number: 14, symbol: 'hearts'},
    // CLUBS
    {number: 1, symbol: 'clubs'},
    {number: 2, symbol: 'clubs'},
    {number: 3, symbol: 'clubs'},
    {number: 4, symbol: 'clubs'},
    {number: 5, symbol: 'clubs'},
    {number: 6, symbol: 'clubs'},
    {number: 7, symbol: 'clubs'},
    {number: 8, symbol: 'clubs'},
    {number: 9, symbol: 'clubs'},
    {number: 10, symbol: 'clubs'},
    {number: 12, symbol: 'clubs'},
    {number: 13, symbol: 'clubs'},
    {number: 14, symbol: 'clubs'},
    // DIAMONGS
    {number: 1, symbol: 'diamonds'},
    {number: 2, symbol: 'diamonds'},
    {number: 3, symbol: 'diamonds'},
    {number: 4, symbol: 'diamonds'},
    {number: 5, symbol: 'diamonds'},
    {number: 6, symbol: 'diamonds'},
    {number: 7, symbol: 'diamonds'},
    {number: 8, symbol: 'diamonds'},
    {number: 9, symbol: 'diamonds'},
    {number: 10, symbol: 'diamonds'},
    {number: 12, symbol: 'diamonds'},
    {number: 13, symbol: 'diamonds'},
    {number: 14, symbol: 'diamonds'},
    // SPADES
    {number: 1, symbol: 'spades'},
    {number: 2, symbol: 'spades'},
    {number: 3, symbol: 'spades'},
    {number: 4, symbol: 'spades'},
    {number: 5, symbol: 'spades'},
    {number: 6, symbol: 'spades'},
    {number: 7, symbol: 'spades'},
    {number: 8, symbol: 'spades'},
    {number: 9, symbol: 'spades'},
    {number: 10, symbol: 'spades'},
    {number: 12, symbol: 'spades'},
    {number: 13, symbol: 'spades'},
    {number: 14, symbol: 'spades'},
 ]
};

module.exports = Config;